# Generated by Django 3.2.9 on 2021-11-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cidade_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('estado_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassificacaoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa_id', models.IntegerField()),
                ('usuario_id', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=200)),
                ('cep', models.IntegerField()),
                ('complemento', models.CharField(max_length=200)),
                ('bairro_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('siga', models.CharField(max_length=2)),
                ('pais', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.IntegerField()),
                ('endereco_id', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa_id', models.IntegerField()),
                ('usuario_id', models.IntegerField()),
                ('carteira_de_trabalho', models.IntegerField()),
                ('cargo', models.CharField(max_length=20)),
                ('salario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario_id', models.IntegerField()),
                ('reserva_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.IntegerField()),
                ('rg', models.IntegerField()),
                ('endereco_id', models.IntegerField()),
                ('carteira_habilitacao', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('nacionalidade', models.CharField(max_length=30)),
                ('naturalidade', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField()),
                ('veiculo_id', models.IntegerField()),
                ('seguro_id', models.IntegerField()),
                ('periodo', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=50)),
                ('privilege', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao_id', models.IntegerField()),
                ('placa', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=20)),
                ('chassi', models.IntegerField()),
                ('renavam', models.IntegerField()),
                ('foto', models.CharField(max_length=20)),
                ('cadeiras', models.IntegerField()),
                ('assentos_elevacao', models.IntegerField()),
                ('gps', models.CharField(max_length=20)),
                ('quilometragem', models.IntegerField()),
                ('nivel_combustivel', models.IntegerField()),
                ('disponibilidade', models.IntegerField()),
                ('valor', models.FloatField()),
            ],
        ),
    ]
